### ISSUE TITLE
Unexpected labels cause failure

### ISSUE THREAD

**Issue by tony-gamble-asos** [microsoft/service-fabric-traefik#10]
If an unexpected label is encountered it causes the fetcher application to crash. This results in no configuration file written at all.

This could cause an outage across all services if the label configuration in just one service is incorrect,

The fetcher should skip a service upon unexpected labels, and should still continue to iterate the remaining services and output the configuration for all the services with good label configuration.

**Comment by nokjuh** [comment]
Here is the error message that happens when there are any unexpected labels such as Traefik v1 labels. Reproducible by running server.exe manually on the cluster.

panic: runtime error: index out of range [2] with length 2

time="2022-03-15T12:58:08Z" level=info msg="Fetching state from cluster"
panic: runtime error: index out of range [2] with length 2

goroutine 5 [running]:
github.com/dariopb/serviceFabricDiscoveryService/pkg/discovery.(*Provider).getKVItemsFromLabels(0xc00006a000, 0xc000143590, 0x5, 0xc0001bf1a0, 0x25)
        C:/projects/sf_stuff/serviceFabricDiscoveryService/pkg/discovery/discoveryworker.go:514 +0x1625
github.com/dariopb/serviceFabricDiscoveryService/pkg/discovery.(*Provider).generateConfiguration(0xc00006a000, 0xc000310000, 0x9, 0x11, 0x0)
        C:/projects/sf_stuff/serviceFabricDiscoveryService/pkg/discovery/discoveryworker.go:430 +0x171
github.com/dariopb/serviceFabricDiscoveryService/pkg/discovery.(*Provider).loadConfiguration(0xc00006a000, 0x676018, 0xc0000503c0, 0xc000057d40)
        C:/projects/sf_stuff/serviceFabricDiscoveryService/pkg/discovery/discoveryworker.go:149 +0x19f
github.com/dariopb/serviceFabricDiscoveryService/pkg/discovery.(*Provider).Provide.func1(0xc00006a000, 0x676018, 0xc0000503c0, 0xc000057d40)
        C:/projects/sf_stuff/serviceFabricDiscoveryService/pkg/discovery/discoveryworker.go:124 +0x50
created by github.com/dariopb/serviceFabricDiscoveryService/pkg/discovery.(*Provider).Provide
        C:/projects/sf_stuff/serviceFabricDiscoveryService/pkg/discovery/discoveryworker.go:123 +0x99

**Comment by egaribay77** [comment]
We cannot consider all scenarios now such as certain invalid v2 labels. This will not cause the fetcher process to crash but will not construct the traefik dynamic config file. This is being logged so can see what component in the label is causing this to fail. 

These invalid v2 labels include when adding an invalid Traefik config option, e.g adding invalid sticky session config “traefik.http.PingerEndpoint0.service.sticky.name", where “cookie” name is missing. 
 
At the moment we only do initial checks to make sure it looks like a valid v2 label (length of label is >= 3, first component contains “traefik”, has the endpoint been enabled to be discovered, second component contains “http” or “tcp”, fourth component contains either “service”, “middlewares”, or “service”, etc. More details can be found in discoveryworker.go [](https://github.com/microsoft/service-fabric-traefik/blob/main/src/serviceFabricDiscoveryService/pkg/discovery/discoveryworker.go#L499)
 
We are leveraging traefik kv way to parse rules (https://github.com/traefik/paerser), so you should be able to use any of the route/middleware, and service rules. After we convert the labels to a tree of nodes the parser handles adding the appropriate metadata and checks against (https://github.com/traefik/genconf) to make sure its an appropriate traefik config. If it is not then the traefik dynamic config file is not constructed.

Let me know what you think and if you have any suggestions.

**Comment by egaribay77** [comment]
This should now be handled by v1.0.0 release (https://github.com/microsoft/service-fabric-traefik/pull/17). As mentioned in the comment above, "To handle skipping all invalid v2 labels the fetcher would have to handle the validation to skip the labels. We don't plan to change this behavior and we can revisit this at a later time". If this is needed and causing issues please create a new issue to track this. This new behavior will be treated as an enhancement.
